# -*- coding: utf-8 -*-
"""LAB RETO 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdseHBHg58Izf4H7dZQcnIppGPzDnQcP
"""

import pandas as pd

file_path= 'Listado_Colegios.csv'
df= pd.read_csv(file_path)

print('Primeras 10 filas del dataset: ')
print(df.head(10))

print('Informacion general del dataset ')
print(df.info())

print('Ultimas 10 filas del dataset: ')
print(df.tail(10))

print('Valores nulos dentro del dataset: ')
print(df.isnull().sum())

print('Valores duplicados dentro del dataset: ')
duplicated_rows = df[df.duplicated()]

if not duplicated_rows.empty:
    print("Filas duplicadas: ")
    print(duplicated_rows)
else:
  print("No hay Valores duplicacos")

print("Nombres de las columnas del dataset: ")
print(df.columns)

print('Valores unicos por columna: ')
print(df.nunique())

print('Porcentaje de valores nulos por columna: ')
print((df.isnull().sum()/len(df)) * 100)

columns_with_nulls = df.columns[df.isnull().any()]
print('Columnas con valores nulos: ')
print(columns_with_nulls)

print('Tipos de datos en nuestro datafrem: ')
print(df.dtypes)

object_columns = df.select_dtypes(include=['object']).columns
print('Columnas con el tipo de dato object:')
print(object_columns)

for col in object_columns:
  print(f"Ejemplos de valores en la columna {col}: ")
  print(df[col].dropna().unique()[:5])

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
print("Columnas con el tipo de dato 'numeric': ")
print(numeric_columns)

for col in numeric_columns:
  print(f"Rango columna {col}: ")
  print(f"Minimo: {df[col].min()}, maximo: {df[col].max()}")

constant_columns = [col for col in df.columns if df[col].nunique() == 1]

if constant_columns:
  print("Columnas con datos constantes: ")
  print(constant_columns)
else:
 print("No hay columnas con datos constantes")