# -*- coding: utf-8 -*-
"""Laboratorio Reto 1 Sesión 26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pL-GP1i6-dm3HM3sEIhM2-hhFkGz2rKP
"""

import pandas as pd

file_path = 'Producto_licores.csv'

df = pd.read_csv(file_path)

#Mostrar las primeras 5 filas

print("Primeras filas del dataset: ")
print(df.head())

#Ver ultimas filas del dataset

print("Ultimas filas del dataset: ")
print(df.tail())

#Motrar informacion general
print("Informacion general del dataset: ")
print(df.info())

#Verificar si hay valores nulos

print("Valores nulos por columna: ")
print(df.isnull().sum())

# Verificar si hay datos duplicados

print("Numero de filas duplicadas: ")
print(df.duplicated().sum())

# Numero de filas y de columnas

print("Numero de filas y columnas: ")
print(df.shape)

#Nombres de las columnas

print("Nombres de las columnas: ")
print(df.columns)

#Resumen columnas categoricas

for column in df.select_dtypes(include=['object']).columns:
  print(f"{column}: ")
  print(df[column].unique()[:5])

# Cantidad de valores unicos por columna

print("Valores unicos por columna: ")
print(df.nunique())

# Columnas con valores unicos bajos

print("Columnas con pocos valores unicos: ")

for column in df.columns:
  unique_count = df[column].nunique()
  if unique_count < 10:
    print(f"{column}: {unique_count} valores unicos")

#Mostrar ejemplos nulos

print("Ejemplos de valores nulos: ")
print(df[df.isnull().any(axis=1)].head())

#Describir columnas de texto o cadenas de caracteres

print("Descripcion de columnas de texto: ")
for column in df.select_dtypes(include=['object']).columns:
  print(f"{column}: {df[column].str.len().describe()}")

# Valores unicos que podrían ser inconsistencias

print("Inconsistencias potenciales: ")
for column in df.select_dtypes(include=['object']).columns:
  print(f"{column}: {df[column].unique()[:10]}")